"""
Django settings for elabsheet project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't&7ag1bqrj)x3r!^htx+*zw)5rqb27_57f$&+25r&-7+w^ql1n_elab'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_js_reverse',
    'whitenoise.runserver_nostatic',
    'commons',
    'logger',
    'cms',
    'lab',
    'instr',
    'grader',
    'feedback',
    'taskpads',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'elabsheet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'elabsheet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    #{
    #    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    #},
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)
STATIC_ROOT = os.path.join(BASE_DIR,'public','static')

##########################
# Additional settings
##########################
SITE_NAME = 'E-Labsheet'
SITE_PREFIX = ''  # override this setting when deployed under URL subpath

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'public','media')

AUTHENTICATION_BACKENDS = (
    'lab.backends.direct_to_lab_authen.DirectToLabBackend',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

####################################
# E-Labsheet Settings
#

# Set this to True to require https login
# Currently doesn't work on development server (running on localhost:8000)
HTTPS_LOGIN = False

### grader settings ###

# Set this to True if you have another grading process running.
SEPARATE_GRADING = False

# Change this to have grader's log somewhere else
GRADER_LOG_DIR = os.path.join(BASE_DIR,'grader/log')

# Set this to True, if you want the grader to save submission outputs
GRADER_OUTPUT_LOG = False

# Set this to True to use "box.cc" as a sandboxing tool, you may want
# to override this in settings_dev.py if you're on an OS that doesn't
# support box (i.e., anything that's not Linux).
USE_BOX_IN_SANDBOX = False

# In case that you use box, enter box's user here.  This user should
# have very minimal access to the system and should not be the user
# who runs elab.  Also, make sure to have user with home dir, because
# mono (c# intepreter) will need it.
BOX_USER = 'elabdummy'              
BOX_GROUP = 'elabdummy'

# This is where all temp scratch box dirs will be created.
# When deployed, it should be move to some other place.
SANDBOX_SCRATCH_DIR = os.path.join(BASE_DIR, 'tmp/elab')

# Default time limit in seconds for grading
DEFAULT_TIME_LIMIT = 2

# Use wall clock instead of CPU time
USE_WALL_CLOCK = True

# Default memory limit in MB for grading
DEFAULT_MEMORY_LIMIT = 2560

### logging settings ###

# log all accesses to previous submissions
# WARNING: this will result in very longer logs
LOG_SUBMISSION_ACCESS = False

### builder settings ###
BUILDERS = {
    #'python' : '/usr/local/bin/python2.7',
    #'python3' : '/usr/local/bin/python3.6',
}

### other settings ###

# mathjax URL prefix and installation location
MATHJAX_ROOT_URL = '/mathjax'
MATHJAX_ROOT_DIR = '/var/www/html/mathjax'
MATHJAX_CONFIG = 'TeX-AMS_CHTML'

####################################
# default taskpads settings
TASKPADS_ENABLED = False
TASKPADS_ANONYMOUS_PARTICIPANT_KEY = 'anonymous'
TASKPADS_ANONYMOUS_SUBMISSION_USERNAME = 'anonymoussub'

try:
    from .settings_local import *
except ImportError:
    pass 

# make sure DirectToLabBackend is included
if 'lab.backends.direct_to_lab_authen.DirectToLabBackend' not in AUTHENTICATION_BACKENDS:
    AUTHENTICATION_BACKENDS = (
            'lab.backends.direct_to_lab_authen.DirectToLabBackend',
            ) + AUTHENTICATION_BACKENDS

####################################
# django-js-reverse settings
#
JS_REVERSE_OUTPUT_PATH = os.path.join(BASE_DIR,'static','js')
JS_REVERSE_SCRIPT_PREFIX = SITE_PREFIX + '/'
