# Generated by Django 2.0.3 on 2018-09-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpads', '0003_auto_20180929_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('post', 'name'), ('post', 'key')},
        ),
    ]
