# Generated by Django 2.0.9 on 2018-10-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskpads', '0004_auto_20180929_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='taskpost',
            name='task_pad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_posts', to='taskpads.TaskPad'),
        ),
    ]
