# Generated by Django 2.0.3 on 2018-05-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180430_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='hint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
