# Generated by Django 2.0.3 on 2018-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180515_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cms.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='generator',
            field=models.TextField(blank=True, help_text='Python code to define variables for child task generation', null=True),
        ),
    ]
