# Generated by Django 2.0.3 on 2018-07-25 14:16

import commons.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20180724_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='testcases',
            field=commons.fields.LongJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='textblanks',
            field=commons.fields.LongJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='generator',
            field=models.TextField(blank=True, help_text='Python code for defining variables to be used during child task generation.<br/>Variables starting with __ will be ignored.', null=True),
        ),
    ]
