# Generated by Django 2.0.3 on 2018-07-25 10:36

from django.db import migrations

def migrate_testcases(apps, schema_editor):
    Task = apps.get_model('cms','Task')
    for task in Task.objects.all():
        testcases = []
        for testcase in task.testcase_set.all():
            testcases.append({
                'input' : testcase.input_data,
                'output' : testcase.solution,
                'capture' : testcase.capture,
                'hint' : testcase.hint,
                'visible' : testcase.visible,
                })
        task.testcases = testcases
        task.save()


def migrate_textblanks(apps, schema_editor):
    Task = apps.get_model('cms','Task')
    for task in Task.objects.all():
        blanks = []
        for blank in task.textblank_set.all():
            blanks.append({
                'id' : blank.blank_id,
                'solution' : blank.solution,
                'score' : blank.score,
                })
        task.textblanks = blanks
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20180725_2116'),
    ]

    operations = [
        migrations.RunPython(migrate_testcases),
        migrations.RunPython(migrate_textblanks)
    ]
