# Generated by Django 2.0.3 on 2018-07-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_move_testcases_textblanks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='task',
        ),
        migrations.RemoveField(
            model_name='textblank',
            name='task',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
        migrations.DeleteModel(
            name='TextBlank',
        ),
    ]
