# Generated by Django 2.0.3 on 2018-07-27 10:08

import cms.fields
import commons.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20180725_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedChildTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('source', models.TextField()),
                ('html_template', models.TextField(blank=True)),
                ('code', cms.fields.CodeField(blank=True)),
                ('testcases', commons.fields.LongJSONField(blank=True, null=True)),
                ('textblanks', commons.fields.LongJSONField(blank=True, null=True)),
                ('testcases_evaluated', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='SuperTask',
        ),
        migrations.CreateModel(
            name='ChildTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cms.task',),
        ),
        migrations.AddField(
            model_name='cachedchildtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Task'),
        ),
        migrations.AlterIndexTogether(
            name='cachedchildtask',
            index_together={('parent_task', 'key')},
        ),
    ]
