# Generated by Django 2.0.3 on 2018-07-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20180727_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='text_grader',
            field=models.TextField(blank=True, help_text='Python script defining the function <tt>grade(index,score,solution,answer)</tt> returning a score for the given answer, or None if the answer is not to be graded.', null=True),
        ),
    ]
