# Generated by Django 2.0.3 on 2018-08-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20180729_1512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cachedchildtask',
            unique_together={('parent_task', 'key')},
        ),
    ]
