# Generated by Django 2.0.9 on 2018-10-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20180814_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Lab'),
        ),
    ]
