FROM cjaikaeo/elab-machine

COPY prepare-instance.sh /root/scripts/
COPY requirements.txt /root/scripts/
COPY stub /root/scripts/stub/

RUN cd /root/scripts \
  && ./prepare-instance.sh --docker \
  && cd output/setup-elab \
  && ./install-user.sh --docker \
  && ./install-elab.sh --docker

RUN DEBIAN_FRONTEND=noninteractive apt-get update  \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y netcat

CMD /bin/bash
