# Generated by Django 2.0.3 on 2018-03-22 07:40

import commons.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lab.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabInSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('disabled', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False)),
                ('hidden_tasks', models.CharField(blank=True, default='', help_text='A comma-separated list of task numbers to be hidden in the lab', max_length=200)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section name or number(s)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional section information')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Course')),
                ('instructors', models.ManyToManyField(blank=True, help_text='Instructor(s) and TA(s) for the section', related_name='instructor_set', to=settings.AUTH_USER_MODEL)),
                ('labs', models.ManyToManyField(through='lab.LabInSection', to='cms.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Academic year in B.E.')),
                ('term', models.IntegerField(choices=[(0, 'summer'), (1, 'first'), (2, 'second')])),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', lab.fields.AnswerField()),
                ('results', lab.fields.GradingResultField()),
                ('compiler_messages', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=40)),
                ('start_grading_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('code_grading_status', models.IntegerField(default=3)),
                ('manual_scores', commons.fields.JSONField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Assignment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Section')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Semester'),
        ),
        migrations.AddField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students enrolled to the section', related_name='student_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labinsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Section'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Section'),
        ),
    ]
