# Generated by Django 2.0.3 on 2018-03-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='labinsection',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['semester']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['submitted_at']},
        ),
    ]
