# Generated by Django 2.0.3 on 2018-05-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressAcl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_list', models.TextField(blank=True, null=True)),
                ('denied_list', models.TextField(blank=True, null=True)),
                ('default_action', models.CharField(choices=[('a', 'allow'), ('d', 'deny')], default='d', max_length=2)),
                ('activated', models.BooleanField(default=True)),
                ('pickled_allowed_list', models.BinaryField()),
                ('pickled_denied_list', models.BinaryField()),
                ('labinsec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab.LabInSection')),
            ],
            options={
                'verbose_name': 'Address ACL',
            },
        ),
    ]
