# Generated by Django 2.0.3 on 2018-05-15 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0004_addressacl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleIpLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('last_access', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='addressacl',
            name='single_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addressacl',
            name='allowed_list',
            field=models.TextField(blank=True, help_text="Enter a single IP (e.g., <tt style='color:green'>158.108.32.8</tt>) or an IP range (e.g., <tt style='color:green'>10.16.5.0 - 10.16.5.255</tt>) in each line.<br/>An empty line or a line starting with <tt style='color:green'>#</tt> will be ignored, but will still be saved.", null=True),
        ),
        migrations.AlterField(
            model_name='addressacl',
            name='denied_list',
            field=models.TextField(blank=True, help_text="Enter a single IP (e.g., <tt style='color:green'>158.108.32.8</tt>) or an IP range (e.g., <tt style='color:green'>10.16.5.0 - 10.16.5.255</tt>) in each line.<br/>An empty line or a line starting with <tt style='color:green'>#</tt> will be ignored, but will still be saved.", null=True),
        ),
        migrations.AlterField(
            model_name='labinsection',
            name='hidden_tasks',
            field=models.CharField(blank=True, default='', help_text='A comma-separated list of assignment IDs to be hidden in the lab', max_length=200),
        ),
        migrations.AddField(
            model_name='singleiplock',
            name='labinsec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.LabInSection'),
        ),
        migrations.AddField(
            model_name='singleiplock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='singleiplock',
            unique_together={('user', 'labinsec')},
        ),
    ]
