# Generated by Django 2.0.3 on 2018-05-20 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0005_auto_20180515_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectToLabAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('labinsec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.LabInSection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='singleiplock',
            options={'verbose_name': 'Single IP Lock'},
        ),
        migrations.AlterField(
            model_name='addressacl',
            name='single_ip',
            field=models.BooleanField(default=False, verbose_name='Enforce Single IP'),
        ),
        migrations.AlterField(
            model_name='singleiplock',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='singleiplock',
            name='labinsec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.LabInSection', verbose_name='Lab in Section'),
        ),
        migrations.AlterUniqueTogether(
            name='directtolabaccount',
            unique_together={('user', 'labinsec')},
        ),
    ]
