# Generated by Django 2.0.3 on 2018-07-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20180520_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directtolabaccount',
            options={'verbose_name': 'direct-to-lab account'},
        ),
    ]
