# Generated by Django 2.0.3 on 2018-07-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_auto_20180724_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='task',
        ),
    ]
