# Generated by Django 2.0.9 on 2018-10-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_remove_submission_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Section'),
        ),
    ]
