# Generated by Django 2.0.9 on 2019-01-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20181003_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
