# Generated by Django 2.0.9 on 2019-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_section_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='directtolabaccount',
            name='submission_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
