# Generated by Django 2.0.3 on 2018-04-30 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0004_auto_20180430_1232'),
        ('lab', '0003_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=20)),
                ('media_id', models.CharField(max_length=64)),
                ('comments', models.TextField(blank=True)),
                ('rating', models.IntegerField()),
                ('lab_in_sec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.LabInSection')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='feedback',
            index_together={('media_type', 'media_id')},
        ),
    ]
